apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app-deployment
  namespace: my-react-appp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      imagePullSecrets:
      - name: reguser
      containers:
        - name: my-react-app
          image: registry.evilcorp.com/my-react-app:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config
            - configMapRef:
                name: db-config
            - configMapRef:
                name: opsearch-config
            - secretRef:
                name: db-credentials
          volumeMounts:
            - name: app-volume
              mountPath: /data
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: app-storage